added precmd and postcmd

diff --git a/rbw.sh.in b/rbw.sh.in
--- a/rbw.sh.in
+++ b/rbw.sh.in
@@ -13,13 +13,22 @@
 # ----------------------------------------------------------------------------
 #
 
-version="rdiff-backup-wrapper 0.9.6.2"
+version="rdiff-backup-wrapper 0.9.7"
 
 etcdir="@prefix@/etc"
 
 fail() {
 	echo $@ >&2
 	exit 1
+}
+
+run_command() {
+	cmd=$1
+	if [ -n "$cmd" ]; then
+		eval "$cmd" "$@"
+
+		[ "$?" -eq "0" ] || fail "Command failed: $cmd"
+	fi
 }
 
 # default values
@@ -107,6 +116,8 @@ fi
 backup() {
 	echo "Backing up $suitename using config $config"
 
+	run_command "$precmd"
+
 	if [ -f "$suitepath/exclude" ]; then
 		excludefile="$(mktemp -t rdiff-backup-exclude)"
 		"$sed" -e "s|^|$sourcedir/|" < "$suitepath/exclude" > "$excludefile"
@@ -122,35 +133,46 @@ backup() {
 	"$rdiff_backup" "$compress" -v "$verbose" --backup-mode --carbonfile --exclude-special-files --exclude-other-filesystems $include $exclude $minsize $maxsize --print-statistics "$source" "$target"
 
 	"$rm" -f "$excludefile" "$includefile"
+
+	run_command "$postcmd"
 }
 
 listinc() {
+	run_command "$precmd"
 	"$rdiff_backup" "$compress" -v "$verbose" --list-increments "$target"
+	run_command "$postcmd"
 }
 
 listincsize() {
+	run_command "$precmd"
 	"$rdiff_backup" "$compress" -v "$verbose" --list-increment-sizes "$target"
+	run_command "$postcmd"
 }
 
 listat() {
+	run_command "$precmd"
 	time="$1"
 	path="$2"
 
 	[ -n "$time" ] || fail "Need a time parameter!"
 
 	"$rdiff_backup" "$compress" -v "$verbose" --list-at-time "$time" "$target/$path"
+	run_command "$postcmd"
 }
 
 listchanged() {
+	run_command "$precmd"
 	time="$1"
 	path="$2"
 
 	[ -n "$time" ] || fail "Need a time parameter!"
 
 	"$rdiff_backup" "$compress" -v "$verbose" --list-changed-since "$time" "$target/$path"
+	run_command "$postcmd"
 }
 
 clean() {
+	run_command "$precmd"
 	time="$1"
 
 	if [ -z "$time" ]; then
@@ -163,15 +185,19 @@ clean() {
 	fi
 
 	"$rdiff_backup" "$compress" -v "$verbose" --force --remove-older-than "$time" "$target"
+	run_command "$postcmd"
 }
 
 restore() {
+	run_command "$precmd"
 	time="$1"
 	path="$2"
 	#"$rdiff_backup" "$compress" -v "$verbose" --restore-as-of "$time" "$target"
+	run_command "$postcmd"
 }
 
 compare() {
+	run_command "$precmd"
 	time="$1"
 
 	if [ -z "$time" ]; then
@@ -195,9 +221,11 @@ compare() {
 	"$rdiff_backup" "$compress" -v "$verbose" $include $exclude --compare-at-time "$time" "$source/$path" "$target/$path"
 
 	"$rm" -f "$excludefile" "$includefile"
+	run_command "$postcmd"
 }
 
 verify() {
+	run_command "$precmd"
 	time="$1"
 
 	if [ -z "$time" ]; then
@@ -207,13 +235,17 @@ verify() {
 	path="$2"
 
 	"$rdiff_backup" "$compress" -v "$verbose" --verify-at-time "$time" "$target/$path"
+	run_command "$postcmd"
 }
 
 cleanup() {
+	run_command "$precmd"
 	"$rdiff_backup" "$compress" -v "$verbose" --check-destination-dir "$target"
+	run_command "$postcmd"
 }
 
 servertest() {
+	run_command "$precmd"
 	if [ -n "$sourcehost" ]; then
 		"$rdiff_backup" "$compress" -v "$verbose" --test-server "$source"
 	fi 
@@ -221,6 +253,7 @@ servertest() {
 	if [ -n "$targethost" ]; then
 		"$rdiff_backup" "$compress" -v "$verbose" --test-server "$target"
 	fi 
+	run_command "$postcmd"
 }
 
 config() {
